// // Conversation with User 0 about cricket
//       Message(users[0], 'Did you catch the cricket match yesterday?', "10:00"),
//       Message(me, 'Yes, it was quite intense!', "10:05"),
//       Message(users[0], 'I was cheering for the home team.', "10:10"),
//       Message(me, 'That match had some incredible moments!', "10:15"),
//       Message(users[0], 'Indeed! The final over was nail-biting.', "10:20"),
//       Message(me, 'It went down to the last ball!', "10:25"),
//       Message(users[0], 'And the crowd went wild!', "10:30"),
//       Message(me, 'I wish I was there in person.', "10:35"),
//       Message(users[0], 'You should come to the stadium next time.', "10:40"),
//       Message(me, 'Ill definitely consider it.', "10:45"),
//       Message(users[0], 'Great! We can enjoy the game together.', "10:50"),
//       Message(me, 'That sounds like a plan!', "10:55"),
//       Message(users[0], 'Looking forward to it!', "11:00"),
//       Message(me, 'Me too!', "11:05"),
//       Message(users[0], 'See you then!', "11:10"),
//       Message(me, 'See you!', "11:15"),
//       Message(users[0], 'Goodbye!', "11:20"),
//       Message(me, 'Goodbye!', "11:25"),

//       // Conversation with User 1 about football
//       Message(
//           users[1], 'Have you been following the football league?', "14:30"),
//       Message(me, 'Yes, my favorite team is doing well!', "14:35"),
//       Message(users[1], 'Whos your favorite player?', "14:40"),
//       Message(me, 'I admire Messi for his skills.', "14:45"),
//       Message(users[1], 'Messi is indeed a legend!', "14:50"),
//       Message(me, 'Hes a game-changer!', "14:55"),
//       Message(users[1], 'Do you play football too?', "15:00"),
//       Message(me, 'I used to play in college.', "15:05"),
//       Message(users[1], 'Thats cool! We should play sometime.', "15:10"),
//       Message(me, 'Sure, Id love to!', "15:15"),
//       Message(users[1], 'Ill bring my friends. Itll be fun!', "15:20"),
//       Message(me, 'Sounds like a plan!', "15:25"),
//       Message(users[1], 'Looking forward to it!', "15:30"),
//       Message(me, 'Me too!', "15:35"),
//       Message(users[1], 'See you on the field!', "15:40"),
//       Message(me, 'Cant wait!', "15:45"),
//       Message(users[1], 'Goodbye!', "15:50"),
//       Message(me, 'Goodbye!', "15:55"),

//       // Conversation with User 2 about flags
//       Message(users[2], 'I saw a flag parade in the city center.', "16:00"),
//       Message(me, 'That sounds like a colorful event!', "16:05"),
//       Message(users[2], 'I found a book about world flags.', "16:10"),
//       Message(me, 'Thats fascinating! Flags have so much history.', "16:15"),
//       Message(users[2], 'Yes, they represent nations and cultures.', "16:20"),
//       Message(me, 'Flags can tell powerful stories.', "16:25"),
//       Message(users[2], 'Absolutely! Do you collect flags?', "16:30"),
//       Message(me, 'I havent, but that sounds like a great hobby.', "16:35"),
//       Message(users[2], 'Its a unique way to learn about the world.', "16:40"),
//       Message(me, 'Ill look into it.', "16:45"),
//       Message(users[2], 'You wont be disappointed!', "16:50"),
//       Message(me, 'I trust your recommendation!', "16:55"),
//       Message(users[2], 'Enjoy your flag journey!', "17:00"),
//       Message(me, 'Thank you! Have a great day!', "17:05"),
//       Message(users[2], 'You too!', "17:10"),
//       Message(me, 'Goodbye!', "17:15"),
//       Message(users[2], 'Goodbye!', "17:20"),

//       // Conversation with User 3 about weather
//       Message(users[3], 'The weather forecast predicts rain this weekend.',
//           "11:00"),
//       Message(me, 'I hope it clears up soon.', "11:05"),
//       Message(users[3], 'Im planning an indoor movie marathon.', "11:10"),
//       Message(me, 'That sounds like a cozy plan!', "11:15"),
//       Message(users[3], 'Ive got my popcorn ready!', "11:20"),
//       Message(me, 'Enjoy your movie marathon!', "11:25"),
//       Message(users[3], 'Thanks! Do you like rainy days?', "11:30"),
//       Message(me, 'I do, its perfect for reading.', "11:35"),
//       Message(users[3], 'Whats your favorite book genre?', "11:40"),
//       Message(me, 'I enjoy science fiction and fantasy.', "11:45"),
//       Message(users[3], 'Great choices! Any book recommendations?', "11:50"),
//       Message(me, 'Have you read "Dune" by Frank Herbert?', "11:55"),
//       Message(users[3], 'No, but Ill check it out!', "12:00"),
//       Message(me, 'Its a classic!', "12:05"),
//       Message(users[3], 'Thanks for the suggestion!', "12:10"),
//       Message(me, 'Youre welcome! Enjoy your weekend.', "12:15"),
//       Message(users[3], 'You too!', "12:20"),
//       Message(me, 'Goodbye!', "12:25"),
//       Message(users[3], 'Goodbye!', "12:30"),

//       // Conversation with User 4 about money
//       Message(users[4], 'Have you ever tried investing in stocks?', "13:00"),
//       Message(me, 'Ive been learning about it recently.', "13:05"),
//       Message(users[4], 'It can be quite profitable if done right.', "13:10"),
//       Message(me, 'I agree, but its also risky.', "13:15"),
//       Message(users[4], 'True, its important to research thoroughly.', "13:20"),
//       Message(me, 'Do you have any stock tips?', "13:25"),
//       Message(users[4], 'Im bullish on tech companies.', "13:30"),
//       Message(me, 'Tech stocks have been performing well.', "13:35"),
//       Message(users[4], 'Exactly! But diversify your portfolio.', "13:40"),
//       Message(me, 'Good advice! Ill keep that in mind.', "13:45"),
//       Message(users[4], 'Invest wisely and be patient.', "13:50"),
//       Message(me, 'Patience is key in investing.', "13:55"),
//       Message(users[4], 'Youre on the right track!', "14:00"),
//       Message(me, 'Thanks for the guidance!', "14:05"),
//       Message(users[4], 'No problem, happy investing!', "14:10"),
//       Message(me, 'Likewise! Have a profitable day!', "14:15"),
//       Message(users[4], 'You too!', "14:20"),
//       Message(me, 'Goodbye!', "14:25"),
//       Message(users[4], 'Goodbye!', "14:30"),

//       // Conversation with User 5 about relationships
//       Message(users[5], 'Hows your relationship going?', "18:00"),
//       Message(me, 'Things are going well with my partner.', "18:05"),
//       Message(users[5], 'Communication is key, right?', "18:10"),
//       Message(me, 'Absolutely, its the foundation!', "18:15"),
//       Message(users[5], 'Any advice for a healthy relationship?', "18:20"),
//       Message(me, 'Trust, respect, and empathy are crucial.', "18:25"),
//       Message(users[5], 'Ill keep that in mind, thanks!', "18:30"),
//       Message(me, 'Youre welcome! How about you?', "18:35"),
//       Message(users[5], 'Im working on it, taking it slow.', "18:40"),
//       Message(me, 'Thats a good approach.', "18:45"),
//       Message(users[5], 'Were both learning and growing.', "18:50"),
//       Message(me, 'Thats the way to do it!', "18:55"),
//       Message(users[5], 'Hope it turns out great!', "19:00"),
//       Message(me, 'Fingers crossed! Have a lovely evening.', "19:05"),
//       Message(users[5], 'You too!', "19:10"),
//       Message(me, 'Goodbye!', "19:15"),
//       Message(users[5], 'Goodbye!', "19:20"),

//       // Conversation with User 6 about animals
//       Message(users[6], 'I visited a farm yesterday and saw cows.', "09:00"),
//       Message(me, 'Cows are such gentle creatures.', "09:05"),
//       Message(users[6], 'I even got to milk a cow!', "09:10"),
//       Message(me, 'That must have been a fun experience!', "09:15"),
//       Message(users[6], 'It was! Have you been to a farm?', "09:20"),
//       Message(me, 'Yes, I have. I love seeing animals up close.', "09:25"),
//       Message(users[6], 'Whats your favorite farm animal?', "09:30"),
//       Message(me, 'I have a soft spot for goats.', "09:35"),
//       Message(users[6], 'Goats are playful and adorable!', "09:40"),
//       Message(me, 'They certainly are!', "09:45"),
//       Message(users[6], 'Lets visit a farm together someday!', "09:50"),
//       Message(me, 'Id love that! Count me in.', "09:55"),
//       Message(users[6], 'Its a plan then!', "10:00"),
//       Message(me, 'Looking forward to it!', "10:05"),
//       Message(users[6], 'Have a great day!', "10:10"),
//       Message(me, 'You too!', "10:15"),
//       Message(users[6], 'Goodbye!', "10:20"),
//       Message(me, 'Goodbye!', "10:25"),
//       // Conversation with User 7 about traveling
//       Message(users[7], 'Have you been on any trips lately?', "09:00"),
//       Message(me, 'Yes, I went hiking in the mountains last month.', "09:05"),
//       Message(users[7], 'That sounds amazing! Any travel plans for the future?',
//           "09:10"),
//       Message(me, 'Im thinking about a beach vacation next.', "09:15"),
//       Message(users[7], 'Beaches are so relaxing!', "09:20"),
//       Message(me, 'I cant wait to feel the sand between my toes.', "09:25"),
//       Message(users[7], 'Dont forget sunscreen!', "09:30"),
//       Message(me, 'Good advice! Safety first.', "09:35"),
//       Message(users[7], 'Enjoy your next adventure!', "09:40"),
//       Message(me, 'Thank you! Its always a pleasure to explore.', "09:45"),
//       Message(users[7], 'Looking forward to your travel photos!', "09:50"),
//       Message(me, 'Ill be sure to share them!', "09:55"),
//       Message(users[7], 'Safe travels!', "10:00"),
//       Message(me, 'Thanks! Have a great day!', "10:05"),
//       Message(users[7], 'You too!', "10:10"),
//       Message(me, 'Goodbye!', "10:15"),
//       Message(users[7], 'Goodbye!', "10:20"),

//       // Conversation with User 8 about technology
//       Message(users[8], 'Have you seen the latest smartphone?', "14:00"),
//       Message(me, 'Yes, it has some impressive features!', "14:05"),
//       Message(users[8], 'Im due for an upgrade.', "14:10"),
//       Message(me, 'Choosing the right phone can be tough.', "14:15"),
//       Message(users[8], 'Do you have any tech recommendations?', "14:20"),
//       Message(me, 'What are you looking for in a phone?', "14:25"),
//       Message(users[8], 'A good camera and long battery life.', "14:30"),
//       Message(me, 'Consider the latest models from top brands.', "14:35"),
//       Message(users[8], 'Ill check them out. Thanks!', "14:40"),
//       Message(me, 'Youre welcome! Enjoy your new gadget!', "14:45"),
//       Message(users[8], 'Ill let you know which one I choose.', "14:50"),
//       Message(me, 'Im curious to hear your decision!', "14:55"),
//       Message(users[8], 'Have a tech-tastic day!', "15:00"),
//       Message(me, 'You too! Stay connected!', "15:05"),
//       Message(users[8], 'Goodbye!', "15:10"),
//       Message(me, 'Goodbye!', "15:15"),

//       // Conversation with User 9 about books
//       Message(users[9], 'Whats the last book you read?', "17:00"),
//       Message(me, 'I recently finished "The Great Gatsby."', "17:05"),
//       Message(users[9], 'F. Scott Fitzgerald is a brilliant author.', "17:10"),
//       Message(me, 'Indeed, his writing is poetic.', "17:15"),
//       Message(users[9], 'Do you have a favorite book?', "17:20"),
//       Message(
//           me, 'Its hard to pick just one, but "1984" is a classic.', "17:25"),
//       Message(users[9], 'I love dystopian novels!', "17:30"),
//       Message(me, 'They make you think about the future.', "17:35"),
//       Message(users[9], 'Whats on your reading list next?', "17:40"),
//       Message(me, 'Im thinking of diving into some science fiction.', "17:45"),
//       Message(users[9], 'That genre offers endless possibilities!', "17:50"),
//       Message(me, 'Exactly! Ready to embark on new adventures.', "17:55"),
//       Message(users[9], 'Happy reading!', "18:00"),
//       Message(me, 'Thank you! Enjoy your book journey too!', "18:05"),
//       Message(users[9], 'You too!', "18:10"),
//       Message(me, 'Goodbye!', "18:15"),
//       Message(users[9], 'Goodbye!', "18:20"),

//       // Conversation with User 10 about food
//       Message(users[10], 'Whats your favorite cuisine?', "12:00"),
//       Message(me, 'Im a fan of Italian food.', "12:05"),
//       Message(users[10], 'Pizza or pasta?', "12:10"),
//       Message(me, 'Both! But I can never say no to pizza.', "12:15"),
//       Message(users[10], 'Any favorite pizza toppings?', "12:20"),
//       Message(me, 'I love a classic Margherita pizza.', "12:25"),
//       Message(users[10], 'Simple and delicious!', "12:30"),
//       Message(me, 'Indeed, its a timeless favorite.', "12:35"),
//       Message(users[10], 'Im a fan of spicy foods.', "12:40"),
//       Message(me, 'Spicy dishes can be quite adventurous!', "12:45"),
//       Message(users[10], 'Whats your go-to dessert?', "12:50"),
//       Message(me, 'Tiramisu is a weakness of mine.', "12:55"),
//       Message(users[10], 'Thats a fantastic choice!', "13:00"),
//       Message(me, 'Do you have a favorite dessert?', "13:05"),
//       Message(users[10], 'I love chocolate lava cake!', "13:10"),
//       Message(me, 'A chocolate lover, I see!', "13:15"),
//       Message(users[10], 'Indulgence at its best!', "13:20"),
//       Message(me, 'Indeed! Bon appétit!', "13:25"),
//       Message(users[10], 'You too!', "13:30"),
//       Message(me, 'Goodbye!', "13:35"),
//       Message(users[10], 'Goodbye!', "13:40"),

//       // Conversation with User 11 about movies
//       Message(users[11], 'Have you seen any good movies lately?', "16:30"),
//       Message(me, 'I watched "Inception" again. Mind-bending!', "16:35"),
//       Message(users[11], 'Christopher Nolan is a genius director.', "16:40"),
//       Message(me, 'His films are always thought-provoking.', "16:45"),
//       Message(users[11], 'Whats your favorite genre?', "16:50"),
//       Message(me, 'I enjoy both sci-fi and thriller genres.', "16:55"),
//       Message(users[11], 'Ever thought of making a film?', "17:00"),
//       Message(me, 'Its a fascinating idea, but Im better with words.', "17:05"),
//       Message(users[11], 'Words can paint vivid pictures too!', "17:10"),
//       Message(me, 'Thats true, the power of storytelling.', "17:15"),
//       Message(users[11], 'Any movie recommendations?', "17:20"),
//       Message(me, 'You should watch "Interstellar" if you havent.', "17:25"),
//       Message(users[11], 'Ill add it to my list!', "17:30"),
//       Message(me, 'Prepare for an epic journey!', "17:35"),
//       Message(users[11], 'Thanks for the tip!', "17:40"),
//       Message(me, 'Youre welcome! Enjoy the movie night.', "17:45"),
//       Message(users[11], 'You too!', "17:50"),
//       Message(me, 'Goodbye!', "17:55"),
//       Message(users[11], 'Goodbye!', "18:00"),

//       // Conversation with User 12 about hobbies
//       Message(users[12], 'Whats your favorite hobby?', "11:30"),
//       Message(me, 'I enjoy painting in my free time.', "11:35"),
//       Message(users[12], 'Art is a great way to express yourself.', "11:40"),
//       Message(me, 'Its my creative outlet.', "11:45"),
//       Message(users[12], 'Do you have a favorite painting style?', "11:50"),
//       Message(me, 'I like impressionism for its emotions.', "11:55"),
//       Message(users[12], 'Ever exhibited your work?', "12:00"),
//       Message(me, 'Ive participated in local art shows.', "12:05"),
//       Message(users[12], 'Thats impressive! Any awards?', "12:10"),
//       Message(me, 'Ive won a few prizes, nothing major.', "12:15"),
//       Message(users[12], 'Keep pursuing your passion!', "12:20"),
//       Message(me, 'I will, thank you for the encouragement.', "12:25"),
//       Message(
//           users[12], 'Looking forward to your future masterpieces!', "12:30"),
//       Message(me, 'I appreciate your support!', "12:35"),
//       Message(users[12], 'Have a colorful day!', "12:40"),
//       Message(me, 'You too! Keep spreading positivity.', "12:45"),
//       Message(users[12], 'Goodbye!', "12:50"),
//       Message(me, 'Goodbye!', "12:55"),

//       // Conversation with User 13 about fitness
//       Message(users[13], 'Do you have a regular workout routine?', "14:30"),
//       Message(me, 'I try to exercise a few times a week.', "14:35"),
//       Message(users[13], 'Cardio or strength training?', "14:40"),
//       Message(me, 'I prefer a mix of both for balance.', "14:45"),
//       Message(users[13], 'Consistency is key!', "14:50"),
//       Message(me, 'Absolutely! Its about long-term health.', "14:55"),
//       Message(users[13], 'Have any fitness goals?', "15:00"),
//       Message(me, 'Im aiming for better endurance and flexibility.', "15:05"),
//       Message(users[13], 'Thats a great approach.', "15:10"),
//       Message(me, 'What about you? Any fitness tips?', "15:15"),
//       Message(users[13], 'Stay hydrated and listen to your body.', "15:20"),
//       Message(me, 'Sound advice! Thanks!', "15:25"),
//       Message(users[13], 'Keep moving and stay active!', "15:30"),
//       Message(me, 'You too! Stay fit and healthy.', "15:35"),
//       Message(users[13], 'Goodbye!', "15:40"),
//       Message(me, 'Goodbye!', "15:45"),

//       // Conversation with User 14 about travel
//       Message(users[14], 'Do you enjoy traveling?', "19:00"),
//       Message(me, 'Yes, exploring new places is a thrill!', "19:05"),
//       Message(users[14], 'Whats your dream destination?', "19:10"),
//       Message(me, 'Ive always wanted to visit Japan.', "19:15"),
//       Message(users[14], 'Japan offers a rich cultural experience.', "19:20"),
//       Message(me, 'Exactly! The food and history are captivating.', "19:25"),
//       Message(users[14], 'Any travel plans for the future?', "19:30"),
//       Message(me, 'Im thinking of a road trip across Europe.', "19:35"),
//       Message(users[14], 'That sounds like an epic journey!', "19:40"),
//       Message(me, 'I hope to create unforgettable memories.', "19:45"),
//       Message(users[14], 'Safe travels on your adventures!', "19:50"),
//       Message(me, 'Thank you! May your journeys be amazing too.', "19:55"),
//       Message(users[14], 'You too!', "20:00"),
//       Message(me, 'Goodbye!', "20:05"),
//       Message(users[14], 'Goodbye!', "20:10"),

//       // Conversation with User 15 about technology
//       Message(users[15], 'Have you seen the latest tech gadgets?', "10:30"),
//       Message(me, 'Yes, technology is advancing rapidly.', "10:35"),
//       Message(users[15], 'Whats your favorite tech innovation?', "10:40"),
//       Message(me, 'Im fascinated by AI and machine learning.', "10:45"),
//       Message(users[15], 'AI has incredible potential!', "10:50"),
//       Message(me, 'Its changing how we live and work.', "10:55"),
//       Message(users[15], 'Do you code or develop software?', "11:00"),
//       Message(me, 'I dabble in coding as a hobby.', "11:05"),
//       Message(users[15], 'Coding is a valuable skill!', "11:10"),
//       Message(me, 'Its a way to bring ideas to life.', "11:15"),
//       Message(users[15], 'Keep exploring the tech world!', "11:20"),
//       Message(me, 'I will! Its a never-ending journey.', "11:25"),
//       Message(users[15], 'Have a tech-savvy day!', "11:30"),
//       Message(me, 'You too! Stay curious!', "11:35"),
//       Message(users[15], 'Goodbye!', "11:40"),
//       Message(me, 'Goodbye!', "11:45"),